# Generated by Django 2.2.10 on 2021-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(default=' ', max_length=60)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('balance', models.IntegerField(default=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
